config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks"
  }
  as :user do
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :answer_boards, except: %i(destroy update) do
    get 'thanks', on: :collection
  end

  resources :question_boards , expect: %i(destroy) do
    resources :questions, module: :question_boards, only: %i(new create)
    resources :invites, module: :question_boards, only: %i(index new create)
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :answer_board, inverse_of: :answers
  belongs_to :question
  
  validates :answer_board, presence: true
  validates :content, presence: true
end

app/models/answer_board.rb
class AnswerBoard < ApplicationRecord
  belongs_to :invite
  has_many :answers, dependent: :destroy, inverse_of: :answer_board
  accepts_nested_attributes_for :answers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :question_board
  delegate :user, to: :question_board

  has_one :answer_board

  has_secure_token :token

  validates :name, presence: true
  validates :email, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :question_board

  validates :title, presence: true
  validates :question_board, presence: true
end

app/models/question_board.rb
class QuestionBoard < ApplicationRecord
  belongs_to :user
  has_many :questions
  has_many :invites

  validates :title, presence: true
  validates :user, presence: true

  before_validation :prepare_questions

  def prepare_questions
    return if self.persisted?

    [
      "この1週間で主に取り組んだことは何ですか？",
      "その中で、良かったこと、継続したいことは何ですか？",
      "逆に、困っていることは何ですか？",
      "その課題を解決するために、何か出来ることはありますか？",
    ].each do |title|
     self.questions.build(title: title)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :trackable, :omniauthable, omniauth_providers: %i(google)

  has_many :question_boards
  has_many :invites, through: :question_boards
  has_many :answer_boards, through: :invites

  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)

    return user if user
    user = User.create( email:    auth.info.email,
                        name:     auth.info.name,
                        provider: auth.provider,
                        uid:      auth.uid,
                        token:    auth.credentials.token,
                        password: Devise.friendly_token[0, 20],
                        meta:     auth.to_yaml
                      )
  end
end

app/controllers/answer_boards_controller.rb
class AnswerBoardsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i(new create thanks)

  before_action :set_token, :set_invite, :set_questions, :check_answer, only: %i(new create)

  def index
    @boards = current_user.answer_boards.order(created_at: :desc)
  end

  def show
    @board = current_user.answer_boards.find(params[:id])
  end

  def new
    @answer_board = @invite.build_answer_board
    @invite.question_board.questions.each do |question|
      @answer_board.answers.build(question: question)
    end
  end

  def create
    @answer_board = @invite.build_answer_board(answer_input_params)

    if @answer_board.save
      redirect_to thanks_answer_boards_url, notice: '回答が送信されました'
    else
      render :new
    end
  end


  def thanks
  end

  private
  def set_token
    @token = params[:token] || params[:answer_board][:token]
  end

  def set_invite
    @invite = Invite.find_by!(token: @token)
  end

  def set_questions
    @questions = @invite.question_board.questions
  end

  def check_answer
    if @invite.answer_board.present?
      redirect_to thanks_answer_boards_url, notice: 'すでに回答済みです'
    end
  end

  def answer_input_params
    params.require(:answer_board).permit(
      answers_attributes: [
        :content,
        :question_id
      ]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
    if user_signed_in?
      redirect_to question_boards_url
    end
  end
end

app/controllers/question_boards/invites_controller.rb
class QuestionBoards::InvitesController < ApplicationController
  before_action :set_question_board, only: %i(index new create)

  def index
    @invites = current_user.invites.order(created_at: :desc)
  end

  def new
    @invite = Invite.new
  end

  def create
    @invite = current_user.invites.build(invite_params)
    if @invite.save
      # deliver_nowでエラーが出た場合はハンドリングしてフォローする
      # エラーが出た場合は再送するなどのボタンが表示されるなど
      # メールサーバー側の問題も起こり得るが、ここではエラーが出る方が親切な気がする
      InviteMailer.creation_email(@invite).deliver_now
      redirect_to question_board_url(@invite.question_board), notice: "#{@invite.name}さんに回答依頼を送信しました。"
    else
      render :new
    end
  end

  private
  def set_question_board
    @question_board = current_user.question_boards.find(params[:question_board_id])
  end

  def invite_params
    params.require(:invite).permit(:name, :email, :question_board_id)
  end
end

app/controllers/question_boards/questions_controller.rb
class QuestionBoards::QuestionsController < ApplicationController
  before_action :set_question_board, only: %i(new create)

  def new
    @question = Question.new
  end

  def create
    @question = @question_board.questions.build(question_params)

    if @question.save
      redirect_to question_board_url(@question_board), notice: "「#{@question.title}」を追加しました🚀"
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title)
  end

  def set_question_board
    @question_board = current_user.question_boards.find(params[:question_board_id])
  end

end

app/controllers/question_boards_controller.rb
class QuestionBoardsController < ApplicationController
  before_action :set_question_board, only: %i(show edit update)

  def index
    @boards = current_user.question_boards.order(created_at: :desc)
  end

  def show
  end

  def edit
  end

  def new
    @question_board = QuestionBoard.new
  end

  def create
    @question_board = current_user.question_boards.build(board_params)

    if @question_board.save
      redirect_to question_board_url(@question_board), notice: '作成しました'
    else
      render :new
    end
  end

  def update
    if @question_board.update(board_params)
      redirect_to question_board_url(@question_board), notice: '更新しました'
    else
      render :edit
    end
  end

  private

  def board_params
    params.require(:question_board).permit(:title)
  end

  def set_question_board
    @question_board = current_user.question_boards.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question_board, only: %i(new create)

  def new
    @question = Question.new
  end

  def create
    @question = @question_board.questions.build(question_params)

    if @question.save
      redirect_to question_board_url(@question_board), notice: "「#{@question.title}」を追加しました🚀"
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title)
  end

  def set_question_board
    @question_board = current_user.question_boards.find(params[:question_board_id])
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google
    @user = User.find_for_google(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answer_boards/_form.html.haml
= form_with(model: answer_board, local: true) do |form|
  .question-box.mt-3
    = form.fields_for :answers do |answer_form|
      - answer = answer_form.object
      %strong= answer.question.title
      - if answer.errors.any?
        .alert.alert-danger
          - answer.errors.full_messages.each do |message|
            #{message}
      .field
        = answer_form.text_area :content,class: 'form-control'
      = answer_form.hidden_field :question_id, value: answer.question.id
  = form.hidden_field :token, value: @token
  .actions.text-right
    = form.submit (yield :submit_label), class: 'btn btn-primary mt-1'

app/views/answer_boards/index.html.haml
.container
  %h1= "#{AnswerBoard.model_name.human}の一覧"
  %ul.list-group
    %li.list-group-item
      .row
        .col-md-4= QuestionBoard.human_attribute_name :title
        .col-md-4= Invite.human_attribute_name :name
        .col-md-4= AnswerBoard.human_attribute_name :created_at
    - @boards.includes(invite:[:question_board]).each do |board|
      %li.list-group-item
        .row
          .col-md-4
            = board.invite.question_board.title
          .col-md-4
            = link_to "#{board.invite.name} さんの回答", answer_board_path(board)
          .col-md-4
            = l(board.created_at, format: :long)

  = link_to "#{QuestionBoard.model_name.human}の一覧へ", question_boards_path

app/views/answer_boards/new.html.haml
%h1 回答の作成

- provide :submit_label, "送信する"
= render 'form', answer_board: @answer_board, questions: @questions

app/views/answer_boards/show.html.haml
= @board.invite.name
= l(@board.created_at, format: :long)

%ul.list-group
  - @board.answers.includes(:question).each do |answer|
    %li.list-group-item
      .question
        %strong= answer.question.title
      .answer= answer.content

= link_to '戻る', answer_boards_path

app/views/answer_boards/thanks.html.haml
回答ありがとうございました🎉

app/views/homes/index.html.haml
.container.mt-5= link_to 'Googleアカウントでログイン', user_google_omniauth_authorize_path

app/views/invites/new.html.haml
%h1 メンバーへの回答依頼

= form_with(model: [@user, @board, @invite], local: true) do |form|
  - if @invite.errors.any?
    #error_explanation.alert.alert-danger
      %ul
        - @invite.errors.full_messages.each do |message|
          %li #{message}

  .field
    = form.text_field :name, placeholder: "名前", class: 'form-control'
  .field
    = form.text_field :email, placeholder: "メールアドレス", class: 'form-control'
  .actions.text-right
    = form.submit '送信', class: 'btn btn-primary mt-1'
    = link_to 'キャンセル', user_question_board_path(@user, @board), class: 'btn btn-default mt-1'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title OneOnOne
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container.mt-3
      - if alert
        %p.alert.alert-danger= alert
      - elsif notice
        %p.alert.alert-success= notice
      = yield

app/views/question_boards/_form.html.haml
= form_with(model: question_board, local: true) do |form|
  - if question_board.errors.any?
    #error_explanation.alert.alert-danger
      - question_board.errors.full_messages.each do |message|
        #{message}

  .field
    名前：
    = form.text_field :title, id: :item_title, placeholder: "タイトル", class: 'form-control'
  .actions.text-right
    = form.submit (yield :submit_label), class: 'btn btn-primary mt-1'

app/views/question_boards/edit.html.haml
%h1= "#{QuestionBoard.model_name.human}名の編集"

- provide :submit_label, "更新"
= render 'form', user: current_user, question_board: @question_board
= link_to 'キャンセル', question_board_path(@question_board), class: 'btn btn-default'

app/views/question_boards/index.html.haml
%h1= "#{QuestionBoard.model_name.human}の一覧"

.container.mt-3.mb-3
  - if @boards.any?
    %ul.list-group
      %li.list-group-item
        .row
          .col-md-8
            = QuestionBoard.human_attribute_name :title
          .col-md-4
            = QuestionBoard.human_attribute_name :created_at
      - @boards.each do |board|
        %li.list-group-item
          .row
            .col-md-8
              = link_to board.title, question_board_path(board)
            .col-md-4
              = l(board.created_at, format: :default)
  - else
    = link_to "#{QuestionBoard.model_name.human}を作成", new_question_board_path
    して1on1をはじめましょう:)

%footer.container
  = link_to "#{QuestionBoard.model_name.human}の作成", new_question_board_path
  = link_to "#{AnswerBoard.model_name.human}の一覧へ", answer_boards_path
  = link_to 'ログアウト', destroy_user_session_path, method: :delete

app/views/question_boards/invites/index.html.haml
%h1= "#{Invite.model_name.human}の一覧"

.container.mt-3.mb-3
  - if @invites.any?
    %ul.list-group
      %li.list-group-item
        .row
          .col-md-8
            = Invite.human_attribute_name :name
          .col-md-4
            = Invite.human_attribute_name :created_at
      - @invites.each do |invite|
        %li.list-group-item
          .row
            .col-md-8
              = link_to "#{invite.name}さんの回答ページ", new_answer_board_path(token: invite.token)
            .col-md-4
              = l(invite.created_at, format: :default)
  - else
    = link_to "#{QuestionBoard.model_name.human}を作成", new_question_board_path
    して1on1をはじめましょう:)

%footer.container
  = link_to "#{QuestionBoard.model_name.human}の作成", new_question_board_path
  = link_to "#{AnswerBoard.model_name.human}の一覧へ", answer_boards_path

app/views/question_boards/invites/new.html.haml
%h1 メンバーへの回答依頼

= form_with(model: [@question_board, @invite], local: true) do |form|
  - if @invite.errors.any?
    #error_explanation.alert.alert-danger
      %ul
        - @invite.errors.full_messages.each do |message|
          %li #{message}
  .field
    = form.text_field :name, placeholder: "名前", class: 'form-control'
  .field
    = form.text_field :email, placeholder: "メールアドレス", class: 'form-control'
  .field
    = form.hidden_field :question_board_id, value: @question_board.id
  .actions.text-right
    = form.submit '送信', class: 'btn btn-primary mt-1'
    = link_to 'キャンセル', question_board_path(@question_board), class: 'btn btn-default mt-1'

app/views/question_boards/new.html.haml
%h1= "#{QuestionBoard.model_name.human}の作成"

- provide :submit_label, "作成"
= render 'form', question_board: @question_board
= link_to 'キャンセル', question_boards_path, class: 'btn btn-default'

app/views/question_boards/questions/_form.html.haml
= form_with(model: [question_board, question], local: true) do |form|
  - if question.errors.any?
    #error_explanation.alert.alert-danger
      - question.errors.full_messages.each do |message|
        #{message}

  .field
    = form.text_field :title, placeholder: "質問を書きます", class: 'form-control'
  .actions.text-right
    = form.submit (yield :submit_label), class: 'btn btn-primary mt-1'
    = link_to 'キャンセル', question_board_path(question_board), class: 'btn btn-default'

app/views/question_boards/questions/_question_list.html.haml
- if questions.empty?
  %div 質問を追加してください
- else
  %ul.list-group
    - questions.each do |question|
      %li.list-group-item= question.title

app/views/question_boards/questions/edit.html.haml
- provide :submit_label, "更新"
= render 'form', board: @board, question: @question

app/views/question_boards/questions/new.html.haml
%h1= "#{Question.model_name.human}の作成"
- provide :submit_label, "作成"

- if @question
  = render 'form', question_board: @question_board, question: @question

app/views/question_boards/show.html.haml
.container
  %h1
    = @question_board.title
  = link_to 'ボード名の編集', edit_question_board_path(@question_board)

  = render "question_boards/questions/question_list", questions: @question_board.questions

  = link_to '質問の追加', new_question_board_question_path(@question_board)

  = link_to 'メンバーへ回答依頼', new_question_board_invite_path(@question_board)

  = link_to '招待一覧', question_board_invites_path(@question_board)

  = link_to '戻る', question_boards_path

app/views/questions/new.html.haml
%h1= "#{Question.model_name.human}の作成"
- provide :submit_label, "作成"

- if @question
  = render 'questions/form', question_board: @question_board, question: @question

app/views/thanks/show.html.haml
回答ありがとうございました🎉

app/views/users/answer_boards/index.html.haml
.container
  %h1 回答の一覧
  %ul.list-group
    %li.list-group-item
      .row
        .col-md-4 タイトル
        .col-md-4 回答者
        .col-md-4 回答日
    - @boards.includes(invite:[:question_board]).each do |board|
      %li.list-group-item
        .row
          .col-md-4
            = board.invite.question_board.title
          .col-md-4
            = link_to "#{board.invite.name} さんの回答", answer_board_path(board)
          .col-md-4
            = l(board.created_at, format: :long)

  = link_to '質問の一覧へ', question_boards_path